export const PREVIOUS_WORK = [
  {
    slug: "akita-tek",
    name: "Akita Tek",
    domain: "akitatek.fr",
    category: "Technology",
    scope: "Website",
  },
  {
    slug: "kissan-ghar",
    name: "Kissan Ghar",
    domain: "kissanghar.pk",
    category: "Agriculture",
    scope: "E-commerce",
  },
  {
    slug: "woodarq",
    name: "Woodarq",
    domain: "woodarq.com",
    category: "Architecture",
    scope: "Website",
  },
  {
    slug: "joco-cups",
    name: "Joco Cups",
    domain: "jococups.com",
    category: "Consumer",
    scope: "E-commerce",
  },
  {
    slug: "offshore-dedi",
    name: "Offshore Dedi",
    domain: "offshorededi.com",
    category: "Hosting",
    scope: "Website",
  },
  {
    slug: "deviate-labs",
    name: "Deviate Labs",
    domain: "deviatelabs.com",
    category: "Growth",
    scope: "Website",
  },
  {
    slug: "matter-capture",
    name: "Matter Capture",
    domain: "capture.matter.city",
    category: "Proptech",
    scope: "Web app",
  },
  {
    slug: "mobikey",
    name: "Mobikey",
    domain: "mobikey.se",
    category: "Mobility",
    scope: "Website",
  },
  {
    slug: "soozal",
    name: "Soozal",
    domain: "soozal.com.au",
    category: "Marketplace",
    scope: "Website",
  },
  {
    slug: "united-way",
    name: "United Way",
    domain: "www.unitedway.org",
    category: "Nonprofit",
    scope: "Project work",
  },
  {
    slug: "tech-vision-365",
    name: "Tech Vision 365",
    domain: "techvision365.netlify.app",
    category: "Technology",
    scope: "Prototype",
  },
  {
    slug: "ejil-enterprises",
    name: "EJIL Enterprises",
    domain: "ejil-enterprises.netlify.app",
    category: "Business",
    scope: "Prototype",
  },
  {
    slug: "structura-surveying",
    name: "Structura Surveying",
    domain: "structurasurveying.com",
    category: "Surveying",
    scope: "Website",
  },
  {
    slug: "company-in-good",
    name: "Company in Good",
    domain: "www.companyingood.net",
    category: "Community",
    scope: "Website",
  },
  {
    slug: "clem-jones-centre",
    name: "Clem Jones Centre",
    domain: "clemjonescentre.com.au",
    category: "Community",
    scope: "Website",
  },
  {
    slug: "moonlit-supports",
    name: "Moonlit Supports",
    domain: "www.moonlitsupports.com.au",
    category: "Care",
    scope: "Website",
  },
  {
    slug: "perfex-painting",
    name: "Perfex Painting",
    domain: "perfexpainting.com.au",
    category: "Trades",
    scope: "Website",
  },
  {
    slug: "ellipses-audio",
    name: "Ellipses Audio",
    domain: "naitch69.wixsite.com/ellipses-audio",
    url: "https://naitch69.wixsite.com/ellipses-audio",
    category: "Audio",
    scope: "Website",
  },
  {
    slug: "governance-central",
    name: "Governance Central",
    domain: "www.governancecentral.com",
    category: "Governance",
    scope: "Website",
  },
  {
    slug: "emperius",
    name: "Emperius",
    domain: "www.emperius.io",
    category: "Technology",
    scope: "Website",
  },
  {
    slug: "fractal-pay",
    name: "Fractal Pay",
    domain: "app.fractalpay.com.au",
    category: "Fintech",
    scope: "Web app",
  },
  {
    slug: "zeebrix",
    name: "Zeebrix",
    domain: "zeebrix.com",
    category: "Platform",
    scope: "Website",
  },
  {
    slug: "devinnovo",
    name: "Devinnovo",
    domain: "devinnovo.com",
    category: "Technology",
    scope: "Website",
  },
  {
    slug: "halo-skin",
    name: "Halo Skin",
    domain: "haloskin.au",
    category: "Beauty",
    scope: "E-commerce",
  },
  {
    slug: "crystals-solution",
    name: "Crystals Solution",
    domain: "crystalssolution.com",
    category: "Services",
    scope: "Website",
  },
  {
    slug: "golrah-traders",
    name: "Golrah Traders",
    domain: "golrahtraders.pk",
    category: "Trading",
    scope: "Website",
  },
  {
    slug: "mcgovern-company",
    name: "McGovern & Company",
    domain: "www.mcgovernandcompany.com",
    category: "Advisory",
    scope: "Website",
  },
  {
    slug: "citra-raya",
    name: "Citra Raya",
    domain: "citraraya.com",
    category: "Property",
    scope: "Website",
  },
  {
    slug: "the-izzara",
    name: "The Izzara",
    domain: "theizzara.com",
    category: "Fashion",
    scope: "E-commerce",
  },
  {
    slug: "holifya",
    name: "Holifya",
    domain: "www.holifya.com",
    category: "Health",
    scope: "Website",
  },
  {
    slug: "romeo-lugan",
    name: "Romeo Lugan",
    domain: "romeolugan.com",
    category: "Personal brand",
    scope: "Website",
  },
  {
    slug: "captive-power-solutions",
    name: "Captive Power Solutions",
    domain: "captivepowersolutions.org",
    category: "Energy",
    scope: "Website",
  },
  {
    slug: "faith-2-fellicity",
    name: "Faith 2 Fellicity",
    domain: "faith2fellicity.com",
    category: "Community",
    scope: "Website",
  },
];
